// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://imwhzpmnypnsngbzmhps.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imltd2h6cG1ueXBuc25nYnptaHBzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5NzAxNTIsImV4cCI6MjA1NTU0NjE1Mn0.x-FKKihIllvhEJYW2jmuSrTHvHeaMpmfa1I2unm3Z4w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);